spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Koi_Vetenarian_Service_Center
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true


openapi:
  service:
    api-docs: Koi-Vetenarian-Service API
    server: http://localhost:8080
    title: Koi-Vetenarian-Service API
    version: 1.0.0
springdoc:
  swagger-ui:
    enabled: true
