spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Koi-Vetenarian-Service-Center
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # Hoặc 'create', 'validate' tùy nhu cầu của bạn
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect # Chỉnh theo version của MySQL
